<?php $this->pageTitle ='Forgot Your Password?' ?>

<?php if ($this->hasFlash('success')): ?>

    <h3>Your password has been changed.</h3>
    <p>You will receive the new, temporary password via email. Once you have logged in with this new password, you may change it by clicking on the "Change Password" link.</p>

<?php else: ?>

    <h3>Reset Your Password</h3>
    <p>Enter your email address below to reset your password.</p>

    <?= $this->form ?>

<?php endif ?>
