<?php $this->pageTitle = 'Your Favorite Pages' ?>

<h3><?= $this->pageTitle ?></h3>

<?php if (count($this->titles) < 1): ?>

    <p>There are currently no pages of content available. Please check back again!</p>

<?php else: ?>

    <?php foreach ($this->titles as $title): ?>

        <div>
            <h4><a href='<?= $this->baseUrl("/page/{$title->id}") ?>'><?= $this->escape($title->title) ?></a></h4>
            <p><?= $this->escape($title->description) ?></p>
        </div>

    <?php endforeach ?>

<?php endif ?>
